FROM ubuntu:24.10

VOLUME /build

ENV BUILD_TYPE=Release
ENV TARGET=stm32f303cb

WORKDIR /usr/local/vcu

COPY . .

# Install system dependencies
RUN apt-get update
RUN apt-get install -y binutils-arm-none-eabi cmake git python3 python3-pip python3-venv

# Install and configure Conan
RUN python3 -m pip install --no-cache-dir conan --break-system-packages
RUN conan remote add libhal-trunk https://libhal.jfrog.io/artifactory/api/conan/trunk-conan
RUN conan config install -sf profiles/baremetal/v2 https://github.com/libhal/conan-config.git
RUN conan profile detect --force

# Run build script and move target binaries
CMD [ "scripts/build_docker.sh" ]
